# Generated by Django 5.2.10 on 2026-01-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST")],
                        max_length=4,
                        verbose_name="HTTP Method",
                    ),
                ),
                (
                    "smiles",
                    models.TextField(
                        blank=True, null=True, verbose_name="SMILES String"
                    ),
                ),
                (
                    "has_molfile",
                    models.BooleanField(
                        default=False, verbose_name="MOL File Uploaded"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Image Width"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Image Height"
                    ),
                ),
                (
                    "image_format",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Image Format"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, verbose_name="Request Successful"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Response Time (ms)"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
