# Generated by Django 5.2.10 on 2026-01-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0002_requestlog_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChemicalCompound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Compound Name"),
                ),
                (
                    "formula",
                    models.CharField(
                        blank=True,
                        help_text="e.g., C2H5OH",
                        max_length=100,
                        verbose_name="Molecular Formula",
                    ),
                ),
                ("smiles", models.TextField(verbose_name="SMILES String")),
                (
                    "molfile",
                    models.TextField(
                        blank=True, null=True, verbose_name="MOL File Content"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "cas_number",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 64-17-5",
                        max_length=20,
                        verbose_name="CAS Number",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Chemical Compound",
                "verbose_name_plural": "Chemical Compounds",
                "ordering": ["name"],
            },
        ),
    ]
