# Generated by Django 5.2.10 on 2026-01-29 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0003_chemicalcompound"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChemicalCompound",
        ),
    ]
