# Generated by Django 5.2.10 on 2026-01-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0004_delete_chemicalcompound"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about this request",
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
