# Generated by Django 5.2.10 on 2026-01-29 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0005_requestlog_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestlog",
            name="description",
        ),
    ]
