# Generated by Django 5.2.10 on 2026-01-30 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0006_remove_requestlog_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestlog",
            name="ip_address",
        ),
    ]
